{% set name = "xbyak" %}
{% set version = "7.29.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/herumi/xbyak/archive/v{{ version }}.tar.gz
  sha256: b543dd4fc6dcc4a65defc6055734595942f9b034861029d6ddfd9231136cc6ce

build:
  number: 0
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/include/xbyak/xbyak.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_mnemonic.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_util.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_bin2hex.h  # [unix]
    - if not exist %LIBRARY_INC%\xbyak\xbyak.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_mnemonic.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_util.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_bin2hex.h exit 1  # [win]

about:
  home: https://github.com/herumi/xbyak
  summary: JIT assembler for x86(IA32), x64(AMD64, x86-64) by C++
  dev_url: https://github.com/herumi/xbyak
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - marcelotrevisani
    - ilya-lavrenov
