{% set name = "xbyak" %}
{% set version = "5.995" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/herumi/xbyak/archive/v{{ version }}.tar.gz
  sha256: 8c5507426803bbc228c63255568a25a7a8661642722fdda6bd9afaafd9be9d19

build:
  number: 0
  skip: true  # [win]
  script:
    - make PREFIX=%LIBRARY_PREFIX% install  # [win]    
    - make PREFIX=$PREFIX install  # [unix]

requirements:
  build:
    - make

test:
  commands:
    - test -f ${PREFIX}/include/xbyak/xbyak.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_mnemonic.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_util.h  # [unix]
    - if not exist %LIBRARY_INC%\xbyak.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak_mnemonic.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak_util.h exit 1  # [win]

about:
  home: https://github.com/herumi/xbyak
  summary: JIT assembler for x86(IA32), x64(AMD64, x86-64) by C++
  dev_url: https://github.com/herumi/xbyak
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - marcelotrevisani
