{% set name = "xbyak" %}
{% set version = "7.33.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/herumi/xbyak/archive/v{{ version }}.tar.gz
  sha256: f77da14716910a0b87afd7b52d5b8bcfc82245abfe3b76190b68e36dad9eb697

build:
  number: 0
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f ${PREFIX}/include/xbyak/xbyak.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_mnemonic.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_util.h  # [unix]
    - test -f ${PREFIX}/include/xbyak/xbyak_bin2hex.h  # [unix]
    - if not exist %LIBRARY_INC%\xbyak\xbyak.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_mnemonic.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_util.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\xbyak\xbyak_bin2hex.h exit 1  # [win]

about:
  home: https://github.com/herumi/xbyak
  summary: JIT assembler for x86(IA32), x64(AMD64, x86-64) by C++
  dev_url: https://github.com/herumi/xbyak
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - marcelotrevisani
    - ilya-lavrenov
